FROM golang:1.13.3-alpine3.10 as builder
ARG VAULT_VERSION=1.3.0
ARG GOOS=linux
ARG GOARCH=amd64
ARG GOPROXY=
ARG MIRROR=
ARG GOPRIVATE=
ARG CMD4CN=
ENV GOPROXY=${GOPROXY}
RUN set -x \
    && sed -i 's#http://dl-cdn.alpinelinux.org#'${MIRROR:=http://dl-cdn.alpinelinux.org}'#g' /etc/apk/repositories \
    && apk update && apk add \
           ca-certificates \
           git \
    && mkdir -pv ${GOPATH}/src/github.com/hashicorp/ \
    && echo "nameserver 8.8.8.8" >> /etc/resolv.conf \
    && echo "13.229.188.59 github.com" >> /etc/hosts \
    && echo "185.199.111.1.3.0 assets-cdn.github.com" >> /etc/hosts \
    && echo "199.59.148.14 github.global.ssl.fastly.net" >> /etc/hosts \
#    && go env -w GOPRIVATE=${GOPRIVATE:=*.icmdb.vip} \
    && go env -w GOPROXY=${GOPROXY} \
#    && git clone https://github.com/hashicorp/vault ${GOPATH}/src/github.com/hashicorp/vault \
    && go get -v github.com/hashicorp/vault \
    && cd ${GOPATH}/src/github.com/hashicorp/vault 
WORKDIR ${GOPATH}/src/github.com/hashicorp/vault
RUN set -x \
    && git checkout v${VAULT_VERSION} \
    && go tool dist list \
    && echo "${GOOS}/${GOARCH}" > ${GOPATH}/bin/platform \
    && GOOS=${GOOS} GOARCH=${GOARCH} go build -v -o ${GOPATH}/bin/vault


FROM golang:1.13.3-alpine3.10
LABEL maintainer="ihanyouqing@gmail.com"
ENV GOBIN=${GOPATH}/bin
ENV VAULT_VERSION=${VAULT_VERSION}
COPY --from=builder ${GOPATH}/bin/platform ${GOPATH}/bin/platform
COPY --from=builder ${GOPATH}/bin/vault    ${GOPATH}/bin/vault
#CMD ["/go/bin/valut", "server", "--config=config.yaml"]
