version: "3"
services:
  linux: 
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: icmdb/vault

  macos:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - GOOS=darwin
        - GOARCH=amd64
        - VAULT_VERSION=1.4.1
        - ALPINE_VERSION=3.11
    image: icmdb/vault:darwin-1.4.1
    volumes:
      - ./vault-darwin/:/vault-darwin/:rw
    command: sh -xc "ls -al /go/bin/ && cp -prfv /go/bin/* /vault-darwin/ && echo Run ./vault-darwin/vault -version"
    restart: always

  vault-server:
    image: icmdb/vault
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - 8200:8200
      - 8201:8201
    command: ["/go/bin/vault", "server", "-dev", "-dev-listen-address=0.0.0.0:8200"]
    restart: always

  vault-agent:
    image: icmdb/vault
    environment:
      - VAULT_AGENT_ADDR=http://vault-server:8200
      - VAULT_LOG_LEVEL=debug
    ports:
      - 8200:8200
    command: ["/go/bin/vault", "agent", "-config=agent.hcl"]
    restart: always
