version: "3"
services:
  builder: 
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: icmdb/vault

  vault-darwin:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - GOOS=darwin
        - VAULT_VERSION=1.3.0
    image: icmdb/vault:darwin-1.3.0
    volumes:
      - ./vault-darwin/:/vault-darwin/:rw
    command: sh -c "ls /go/bin/ && \cp /go/bin/* /vault-darwin/"
    restart: always

  vault-server:
    image: icmdb/vault
    environment:
     - XXX=
    ports:
      - 8200:8200
      - 8201:8201
    command: ["/go/bin/vault", "server", "-dev", "-dev-listen-address=0.0.0.0:8200"]
    restart: always

  vault-agent:
    image: icmdb/vault
    environment:
      - VAULT_AGENT_ADDR=0.0.0.0:8200
      - VAULT_LOG_LEVEL=debug
    command: ["/go/bin/vault", "agent", "-config=agent.hcl"]
    restart: always
